### ISSUE TITLE
Visible Whitespace

### ISSUE THREAD

**Issue by blainesch** [blainesch/regex-mvp#6]
When displaying a space or a tab it might be difficult to see.

We could replace the space with a dot (`.`) or an underscore (`_`) and tabs with an em-dash (`—`).

Another alternative would be to color them. Tabs one color and spaces another.

Maybe a combination of both?

**Comment by afaur** [comment]
maybe a http://www.fileformat.info/info/unicode/char/2022/index.htm for spaces
maybe use an arrow for tab http://www.fileformat.info/info/unicode/char/290d/index.htm

**Comment by blainesch** [comment]
I used a bullet and an em-dash. I also inverted the colors.

![05_26_15 at 01 56 06pm](https://cloud.githubusercontent.com/assets/769039/7823244/fded0724-03ae-11e5-92a7-ff70bb6bc65c.png)

**Comment by blainesch** [comment]
Fixed by 3cc7655fc5379620c7c87e24ab5c608654059e7b
